services:
  mysql:
    image: mysql:8.0
    container_name: meu-sql-teste
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: meu_banco 
      MYSQL_USER: usuario
      MYSQL_PASSWORD: teste
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    
volumes:
  mysql_data:
 
  

    
      