services:
 postgres :
    image: postgres:latest
    container_name: desafio-8
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
     - desafio-8:/var/lib/postgresql/dat
    networks:
      - desafio-8
    ports:
      - "5432:5432"
 pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-desafio-8
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on: 
      - postgres
    networks:
      - desafio-8
    volumes:
      - desafio-8-pgadmin:/var/lib/pgadmin
    
    
volumes:
  desafio-8:
  desafio-8-pgadmin:
  
networks:
  desafio-8:
   
      
  
    
  
